import paramiko, sys, io, time

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('165.227.102.188', username='root', password='theturnAi2026fm', timeout=15)

# Reset to clean v1.0.0
stdin, stdout, stderr = ssh.exec_command('docker stop selfheal-app; docker rm selfheal-app; docker run -d --name selfheal-app -p 9090:9090 -e FAIL_MODE=false -e APP_VERSION=1.0.0 --restart unless-stopped selfheal-app:latest')
stdout.read()
stdin, stdout, stderr = ssh.exec_command('docker tag selfheal-app:latest selfheal-app:stable')
stdout.read()
time.sleep(3)

print()
print('=============================================')
print('  AI SELF-HEALING CI/CD - LIVE DEMO')
print('=============================================')
print()
print('STEP 1: App is running and HEALTHY')
print('>>> curl http://165.227.102.188:9090/health')
stdin, stdout, stderr = ssh.exec_command('curl -s http://localhost:9090/health | python3 -m json.tool')
print(stdout.read().decode('utf-8'))
time.sleep(3)

print('=============================================')
print('STEP 2: DEPLOYING BROKEN CODE (v2.0.0)')
print('=============================================')
print('>>> git push origin main  (simulating bad deployment)')
print('>>> docker deploy with FAIL_MODE=true...')
stdin, stdout, stderr = ssh.exec_command('docker stop selfheal-app; docker rm selfheal-app; docker run -d --name selfheal-app -p 9090:9090 -e FAIL_MODE=true -e APP_VERSION=2.0.0-broken --restart unless-stopped selfheal-app:latest')
stdout.read()
time.sleep(4)
print('>>> Deploy complete.')
print()

print('=============================================')
print('STEP 3: HEALTH CHECK FAILS!')
print('=============================================')
print('>>> curl http://165.227.102.188:9090/health')
stdin, stdout, stderr = ssh.exec_command('curl -s http://localhost:9090/health | python3 -m json.tool')
print(stdout.read().decode('utf-8'))
time.sleep(3)

print('=============================================')
print('STEP 4: AI SELF-HEALING TRIGGERED')
print('=============================================')
print('>>> Sending logs to GPT-4o for analysis...')
print()
cmd = 'cd /opt/ai-selfheal-cicd && source .env && HEALTH_URL=http://localhost:9090/health python3 scripts/ai_healer.py'
stdin, stdout, stderr = ssh.exec_command(cmd, timeout=60)
print(stdout.read().decode('utf-8'))
time.sleep(3)

print('=============================================')
print('STEP 5: APP RECOVERED - ZERO HUMAN INTERVENTION')
print('=============================================')
print('>>> curl http://165.227.102.188:9090/health')
stdin, stdout, stderr = ssh.exec_command('curl -s http://localhost:9090/health | python3 -m json.tool')
print(stdout.read().decode('utf-8'))

print('=============================================')
print('  DEMO COMPLETE!')
print('  v1.0.0 healthy -> v2.0.0 broke -> AI detected')
print('  -> ROLLBACK automatic -> App recovered')
print('=============================================')

ssh.close()
input('\nPress Enter to close...')
